name: fresha_mobile
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  card_swiper: ^3.0.1
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  # google_fonts: ^6.1.0
  flex_color_scheme: ^7.3.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  google_fonts: 6.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_core_platform_interface: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env